ms_payments: {
  jetstream: enabled

  users: [
    {
      user: ms_payments_app
      password: "$2a$12$IMmmkTnS6kvDItnfZJpZgex7p0B5aEU3.smCclWaEDII5Qvlq8B.u"
      permissions: {
        publish: {
          allow: [
            "payments_status"
            "payments_status.>"
            "$JS.API.>"
            "_INBOX.>"
          ]
        }
        subscribe: {
          allow: [
            "payments_status"
            "payments_status.>"
            "payments_status_dlq"
            "payments_status_dlq.>"
            "$JS.API.CONSUMER.>"
            "_INBOX.>"
            "_REQS.>"
          ]
        }
      }
    }
  ]
}